### ISSUE TITLE
Question about key distribution 

### ISSUE THREAD

**Issue by kim** [domodwyer/bloom2#6]
Hi,

I came here while researching a Bloom filter construction which would yield minimal transmission size and fast intersection. Your construction seems interesting, because it also minimises the number of hash functions (in fact, you’re using only one).

From a cursory glance over the code, it is unclear to me, however, when exactly this will result in space savings. Usually, we would expect the set bits in a bloom filter to be essentially randomly distributed, and I’m having trouble to see how this would be different here. Iow, as the load factor increases, the probability of the block map to be all-1s approaches 1. This means that we’ll have the underlying blocks of the bitmap initialised, even if they are still sparse (ie. contain mostly zeroes).

It’s possible that I’m missing something obvious. Would you mind explaining what that might be?

Thanks!

**Comment by domodwyer** [comment]
Hi @kim 

You are roughly correct - a uniformly distributed hash will cause uniformly distributed 1 bits in the bitmap. As this algorithm splits the 1 bits into groups of 64 bits, a 1 somewhere will allocate a block of 64 bits for it. However as noted in the readme, using a heavily loaded bloom filter (that is, one with lots of 1 bits in the bitset) is impractical - the false positive rate begins to make the filter useless. This property allows us to optimistically save space by splitting the bitset into lazily allocated blocks, knowing that the bloom filter is unlikely to ever be close to fully loaded.

That said now const generics are in place, the bitset can be further split into smaller blocks to tune the block allocation & space tradeoffs (currently a block is 64bits, but could go as low as 8 bits). 

I suggest you measure the load factor and resulting bitmap size for your use case to understand the real-world numbers - I hope this implementation is helpful, but if not it will likely help you find one that is :)

This algorithm should provide extremely fast bitwise operations / intersections (faster than a raw bitmap!) which is what I needed at the time - I am interested to hear more about your use case and results!

Dom
