### ISSUE TITLE
Question regarding actual memory usage savings

### ISSUE THREAD

**Issue by Jimmy-Z** [domodwyer/bloom2#7]
I'd guessing for high loads, compared to a plain bloom filter with just a block of memory, the tree overhead (pointers and stuff) might invalidate the memory saving benefit, do you have data on that, like memory saving for different loads, and at which load bloom2 becomes beneficial?

I could write some tests but wondering if you already have that data on hand.

Thanks.

**Comment by domodwyer** [comment]
Hey Jimmy,

It works out to be ~1.5% - so if a fully loaded bloom filter (every bit set) was 100%, a fully loaded bloom2 instance takes 101.5%. Obviously the use case where the tradeoff makes sense is for partially filled bloom filter, where the 1.5% overhead is worth spending to gain a large reduction in total size proportional to the load factor.

I don't have any actual numbers on hand for load factor -> savings, as it's dependent on your hash and input data, but unless your heavily loading the bloom filter (which seems unlikely given the false probably rates) I would expect it to be a net saving. I'd always recommend benchmarking this (or any other library) for your own use case!

Dom
